--新增 发送CC手工执行任务表
CREATE TABLE "REPORT"."R_CC_SEND_RESULT" (
 "CC_SEND_RESULT_ID" NUMBER(20,0) NOT NULL,
 "BATCH_NO" VARCHAR2(50),
 "REPORT_TYPE" VARCHAR2(50),
 "CC_FILE" VARCHAR2(200),
  "SEND_TIMES" NUMBER(10,0),
   "STATUS" VARCHAR2(50),
    "SEND_RESULT" VARCHAR2(2000),
     "CREATED_BY_ID" NUMBER(19,0),
     "CREATED_DATE" DATE,
     "UPDATED_BY_ID" NUMBER(19,0),
      "UPDATED_DATE" DATE,
      PRIMARY KEY("CC_SEND_RESULT_ID"));
/
COMMENT ON COLUMN "REPORT"."R_CC_SEND_RESULT"."BATCH_NO" IS '发送批次';
/
COMMENT ON COLUMN "REPORT"."R_CC_SEND_RESULT"."REPORT_TYPE" IS '数据类型 详见：com.ford.report.entity.common.ReportType';
/
COMMENT ON COLUMN "REPORT"."R_CC_SEND_RESULT"."CC_FILE" IS '发送cc的文件';
/
COMMENT ON COLUMN "REPORT"."R_CC_SEND_RESULT"."SEND_TIMES" IS '发送次数';
/
COMMENT ON COLUMN "REPORT"."R_CC_SEND_RESULT"."STATUS" IS '发送状态:成功，失败';

CREATE SEQUENCE "REPORT"."SEQ_R_CC_SEND_RESULT_ID" INCREMENT BY 1 START WITH 1 MAXVALUE 9999999999999999999999999999 MINVALUE 1 NOCYCLE CACHE 20 NOORDER;

ALTER TABLE "REPORT"."R_CC_SEND_RESULT"   ADD "DATE_NO" VARCHAR2(20)  ADD "CC_PATH" VARCHAR2(200);
/
COMMENT ON COLUMN "REPORT"."R_CC_SEND_RESULT"."DATE_NO" IS '日期批次号 同以往的日期批次号含义';
/
COMMENT ON COLUMN "REPORT"."R_CC_SEND_RESULT"."CC_PATH" IS 'cc文件存储目录';

--统一任务执行表 R_BATCH_TASK 新增字段 批处理执行次数 和 批处理执行结果 以及 批处理数据时间

ALTER TABLE "REPORT"."R_BATCH_TASK"   ADD "RUN_TIMES" NUMBER(1,0)  ADD "BATCH_RESULT" VARCHAR2(4000BYTE) ADD "BATCH_DATE" DATE NULL;
/
COMMENT ON COLUMN "REPORT"."R_BATCH_TASK"."RUN_TIMES" IS '批处理执行次数  业务 处理3次及以上，任务则认为 失败';
/
COMMENT ON COLUMN "REPORT"."R_BATCH_TASK"."BATCH_RESULT" IS '批处理执行 结果';
/
COMMENT ON COLUMN "REPORT"."R_BATCH_TASK"."BATCH_DATE" IS '批次处理那一日的数据';

--新增发送CC状态字段

ALTER TABLE "REPORT"."R_IMPORT_DATA_COUNT"   ADD "SEND_CC_STATUS" VARCHAR2(50);
/
COMMENT ON COLUMN "REPORT"."R_IMPORT_DATA_COUNT"."SEND_CC_STATUS" IS '发送CC的状态 未发送，已发送 ';

--新增odp_type类型字段,dp_id唯一标识
ALTER TABLE "REPORT"."R_DMS_CAR_OWNER"   ADD "ODP_TYPE" VARCHAR2(50) ADD "DP_ID" VARCHAR2(50);
/
COMMENT ON COLUMN "REPORT"."R_DMS_CAR_OWNER"."ODP_TYPE" IS 'odp类型: 参见：com.ford.report.entity.odp.common.OdpType';
/
COMMENT ON COLUMN "REPORT"."R_DMS_CAR_OWNER"."DP_ID" IS '唯一编码（yyyyMMdd+9为sequence）';
--新增odp_type类型字段，dp_id唯一标识
ALTER TABLE "REPORT"."R_DMS_NEW_CAR_OWNER"   ADD "ODP_TYPE" VARCHAR2(50) ADD "DP_ID" VARCHAR2(50);
/
COMMENT ON COLUMN "REPORT"."R_DMS_NEW_CAR_OWNER"."ODP_TYPE" IS 'odp类型: 参见：com.ford.report.entity.odp.common.OdpType';
/
COMMENT ON COLUMN "REPORT"."R_DMS_NEW_CAR_OWNER"."DP_ID" IS '唯一编码（yyyyMMdd+9为sequence）';
--dp_id唯一标识
ALTER TABLE REPORT.R_RAW_CAR_OWNER ADD DP_ID VARCHAR2(50) NULL;
ALTER TABLE REPORT.R_CC_OB_CAR_OWNER ADD DP_ID VARCHAR2(50) NULL;
ALTER TABLE REPORT.R_CC_OB_CAR_OWNER ADD REBOUND_REASON VARCHAR2(500) NULL;


--空错号 添加字段
ALTER TABLE "REPORT"."R_ODP_UN_CONT_OWNER"   ADD "OB_DATE" DATE  ADD "CHANNEL" VARCHAR2(50BYTE);
/
COMMENT ON COLUMN "REPORT"."R_ODP_UN_CONT_OWNER"."OB_DATE" IS '呼叫中心拨打日期';
/
COMMENT ON COLUMN "REPORT"."R_ODP_UN_CONT_OWNER"."CHANNEL" IS '渠道来源，【新车主，呼叫中心】';

--新的数据转换结果表 新增 是否弹回字段
ALTER TABLE "REPORT"."R_CC_NEW_OB_RESULT"   ADD "REBOUND" NUMBER(1,0);
/
COMMENT ON COLUMN "REPORT"."R_CC_NEW_OB_RESULT"."REBOUND" IS '是否弹出，1 弹回；0 不弹回；详见：com.ford.report.entity.odp.ob.Rebound';

--ODP车主分析报告 新增报告年月字段
ALTER TABLE "REPORT"."R_ODP_OWNER"   ADD "YEAR_MONTH" VARCHAR2(50BYTE);
/
COMMENT ON COLUMN "REPORT"."R_ODP_OWNER"."YEAR_MONTH" IS '报告年月';
ALTER TABLE "REPORT"."R_ODP_AFTER_OWNER"   ADD "YEAR_MONTH" VARCHAR2(50BYTE);
/
COMMENT ON COLUMN "REPORT"."R_ODP_AFTER_OWNER"."YEAR_MONTH" IS '报告年月';
ALTER TABLE "REPORT"."R_ODP_BEFORE_OWNER"   ADD "YEAR_MONTH" VARCHAR2(50BYTE);
/
COMMENT ON COLUMN "REPORT"."R_ODP_BEFORE_OWNER"."YEAR_MONTH" IS '报告年月';
ALTER TABLE REPORT.R_CC_OB_RESULT ADD DP_ID VARCHAR2(50) NULL;
ALTER TABLE REPORT.R_CC_OB_RESULT ADD REBOUND_REASON VARCHAR2(1000) NULL;
ALTER TABLE REPORT.R_CC_OB_RESULT ADD REBOUND INT NULL;
--增加报告ID
ALTER TABLE REPORT.R_ODP_OWNER ADD ANALYSIS_ID INT NULL;
COMMENT ON COLUMN REPORT.R_ODP_OWNER.ANALYSIS_ID IS '月报告ID';
ALTER TABLE REPORT.R_ODP_OWNER ADD ANALYSIS_NO VARCHAR2(50) NULL;
COMMENT ON COLUMN REPORT.R_ODP_OWNER.ANALYSIS_NO IS '月报告编号';
ALTER TABLE REPORT.R_ODP_OWNER ADD QUARTZ_ANALYSIS_ID INT NULL;
COMMENT ON COLUMN REPORT.R_ODP_OWNER.QUARTZ_ANALYSIS_ID IS '季度报告ID';
ALTER TABLE REPORT.R_ODP_OWNER ADD QUARTZ_ANALYSIS_NO VARCHAR2(50) NULL;
COMMENT ON COLUMN REPORT.R_ODP_OWNER.QUARTZ_ANALYSIS_NO IS '季度报告编号';
ALTER TABLE REPORT.REPORT_ODP_DEALER_ANALYSIS ADD EMAIL VARCHAR2(100) NULL;
COMMENT ON COLUMN REPORT.REPORT_ODP_DEALER_ANALYSIS.EMAIL IS '接收邮件的地址';