-- auto-generated definition
CREATE SEQUENCE SEQ_WE_SURVEY_CONFIG
MAXVALUE 999999999999999999999999
CYCLE
CACHE 500
/

-- auto-generated definition
CREATE SEQUENCE SEQ_WE_SURVEY_CALLBACK
MAXVALUE 999999999999999999999999
CYCLE
CACHE 500
/

-- auto-generated definition
CREATE SEQUENCE SEQ_WE_REDIRECTION
MAXVALUE 999999999999999999999999
CYCLE
CACHE 500
/







-- auto-generated definition
CREATE TABLE WE_REDIRECTION
(
  ID              NUMBER(11) NOT NULL
    CONSTRAINT WE_REDIRECTION_PK
    PRIMARY KEY,
  STATE           VARCHAR2(40)  DEFAULT NULL,
  URL             VARCHAR2(255) DEFAULT NULL,
  REMARK          VARCHAR2(20),
  CREATED_BY_ID   NUMBER(11),
  CREATED_DATE    DATE          DEFAULT sysdate,
  UPDATED_BY_ID   NUMBER(11),
  UPDATED_DATE    DATE          DEFAULT sysdate,
  OPT_COUNTER     NUMBER(11),
  DELETED_DATE    DATE,
  MARK_FOR_DELETE NUMBER(1)     DEFAULT 0
)
/
COMMENT ON COLUMN WE_REDIRECTION.ID IS '主键'
/
COMMENT ON COLUMN WE_REDIRECTION.STATE IS '渠道 区分入口程序'
/
COMMENT ON COLUMN WE_REDIRECTION.URL IS '授权跳转的URL'
/
COMMENT ON COLUMN WE_REDIRECTION.REMARK IS '备注说明'
/
COMMENT ON COLUMN WE_REDIRECTION.CREATED_BY_ID IS '创建人ID'
/
COMMENT ON COLUMN WE_REDIRECTION.CREATED_DATE IS '创建时间'
/
COMMENT ON COLUMN WE_REDIRECTION.UPDATED_BY_ID IS '更新人ID'
/
COMMENT ON COLUMN WE_REDIRECTION.UPDATED_DATE IS '更新时间'
/
COMMENT ON COLUMN WE_REDIRECTION.OPT_COUNTER IS '记录操作次，乐观锁'
/
COMMENT ON COLUMN WE_REDIRECTION.DELETED_DATE IS '删除时间'
/
COMMENT ON COLUMN WE_REDIRECTION.MARK_FOR_DELETE IS '是否标记删除 0 未删除   1 表示删除'
/



-- auto-generated definition
CREATE TABLE WE_SURVEY_CALLBACK
(
  ID              NUMBER(11) NOT NULL
    CONSTRAINT WE_SURVEY_CALLBACK_PK
    PRIMARY KEY,
  OPEN_ID         VARCHAR2(100) DEFAULT NULL,
  SHORT_ID        VARCHAR2(20),
  STATUS          VARCHAR2(40)  DEFAULT NULL,
  TIMESTAMP       VARCHAR2(20),
  SIGNATURE       VARCHAR2(40),
  CREATED_BY_ID   NUMBER(11),
  CREATED_DATE    DATE          DEFAULT sysdate,
  UPDATED_BY_ID   NUMBER(11),
  UPDATED_DATE    DATE          DEFAULT sysdate,
  OPT_COUNTER     NUMBER(11),
  DELETED_DATE    DATE,
  MARK_FOR_DELETE NUMBER(1)     DEFAULT 0
)
/
COMMENT ON COLUMN WE_SURVEY_CALLBACK.ID IS '主键'
/
COMMENT ON COLUMN WE_SURVEY_CALLBACK.OPEN_ID IS '微信openId'
/
COMMENT ON COLUMN WE_SURVEY_CALLBACK.SHORT_ID IS '问卷项目短ID'
/
COMMENT ON COLUMN WE_SURVEY_CALLBACK.STATUS IS '答题状态：有效答卷； 无效答卷'
/
COMMENT ON COLUMN WE_SURVEY_CALLBACK.TIMESTAMP IS '回调时间戳'
/
COMMENT ON COLUMN WE_SURVEY_CALLBACK.SIGNATURE IS '签名'
/
COMMENT ON COLUMN WE_SURVEY_CALLBACK.CREATED_BY_ID IS '创建人ID'
/
COMMENT ON COLUMN WE_SURVEY_CALLBACK.CREATED_DATE IS '创建时间'
/
COMMENT ON COLUMN WE_SURVEY_CALLBACK.UPDATED_BY_ID IS '更新人ID'
/
COMMENT ON COLUMN WE_SURVEY_CALLBACK.UPDATED_DATE IS '更新时间'
/
COMMENT ON COLUMN WE_SURVEY_CALLBACK.OPT_COUNTER IS '记录操作次，乐观锁'
/
COMMENT ON COLUMN WE_SURVEY_CALLBACK.DELETED_DATE IS '删除时间'
/
COMMENT ON COLUMN WE_SURVEY_CALLBACK.MARK_FOR_DELETE IS '是否标记删除 0 未删除   1 表示删除'
/




-- auto-generated definition
CREATE TABLE WE_SURVEY_CONFIG
(
  ID              NUMBER(11) NOT NULL
    CONSTRAINT WE_SURVEY_CONFIG_PK
    PRIMARY KEY,
  SHORT_ID        VARCHAR2(40),
  NEED_CALLBACK   NUMBER(1),
  REDIRECT_URL    VARCHAR2(255),
  CALLBACK_URL    VARCHAR2(255),
  REMARK          VARCHAR2(255),
  CREATED_BY_ID   NUMBER(11),
  CREATED_DATE    DATE      DEFAULT sysdate,
  UPDATED_BY_ID   NUMBER(11),
  UPDATED_DATE    DATE      DEFAULT sysdate,
  OPT_COUNTER     NUMBER(11),
  DELETED_DATE    DATE,
  MARK_FOR_DELETE NUMBER(1) DEFAULT 0
)
/
COMMENT ON COLUMN WE_SURVEY_CONFIG.ID IS '主键'
/
COMMENT ON COLUMN WE_SURVEY_CONFIG.SHORT_ID IS '问卷项目短ID'
/
COMMENT ON COLUMN WE_SURVEY_CONFIG.NEED_CALLBACK IS '是否需要回调 1. 需要  0. 不需要'
/
COMMENT ON COLUMN WE_SURVEY_CONFIG.REDIRECT_URL IS '答题完跳转链接'
/
COMMENT ON COLUMN WE_SURVEY_CONFIG.CALLBACK_URL IS '回调地址'
/
COMMENT ON COLUMN WE_SURVEY_CONFIG.REMARK IS '备注'
/
COMMENT ON COLUMN WE_SURVEY_CONFIG.CREATED_BY_ID IS '创建人ID'
/
COMMENT ON COLUMN WE_SURVEY_CONFIG.CREATED_DATE IS '创建时间'
/
COMMENT ON COLUMN WE_SURVEY_CONFIG.UPDATED_BY_ID IS '更新人ID'
/
COMMENT ON COLUMN WE_SURVEY_CONFIG.UPDATED_DATE IS '更新时间'
/
COMMENT ON COLUMN WE_SURVEY_CONFIG.OPT_COUNTER IS '记录操作次，乐观锁'
/
COMMENT ON COLUMN WE_SURVEY_CONFIG.DELETED_DATE IS '删除时间'
/
COMMENT ON COLUMN WE_SURVEY_CONFIG.MARK_FOR_DELETE IS '是否标记删除 0 未删除   1 表示删除'
/

