CREATE TABLE "CRM"."WE_PC_INFO" (
  "ID"              NUMBER(11, 0) NOT NULL,
  "INFO_TYPE_IM_ID" NUMBER(11, 0),
  "TITLE"           VARCHAR2(500),
  "CONTENT"         VARCHAR2(4000),
  "INDEXED"         NUMBER(1, 0),
  "TAGS"            VARCHAR2(100),
  "CREATED_DATE"    DATE,
  "UPDATED_DATE"    DATE,
  "CREATED_BY_ID"   NUMBER(11, 0),
  "UPDATED_BY_ID"   NUMBER(11, 0)
);

CREATE TABLE "CRM"."WE_PC_ICON_MENU" (
  "ID"            NUMBER(11, 0) NOT NULL,
  "NAME"          VARCHAR2(50),
  "TYPE_ID"        NUMBER(50, 0),
  "TYPE_NAME"     VARCHAR2(250),
  "IMAGE_URL"     VARCHAR2(250),
  "ORDER_"        NUMBER(6, 0),
  "IMG_WIDTH"     VARCHAR2(20),
  "RECOMMEND"         NUMBER(1, 0),
  "RECOMMEND_END_TIME"  DATE,
  "HREF"     VARCHAR2(250),
  "CREATED_DATE"  DATE,
  "UPDATED_DATE"  DATE,
  "CREATED_BY_ID" NUMBER(11, 0),
  "UPDATED_BY_ID" NUMBER(11, 0)
);


CREATE TABLE "CRM"."WE_PC_USER_ICON_MENU" (
  "ID"            NUMBER(11, 0) NOT NULL,
  "OPENID"          VARCHAR2(50),
  "VIN"          VARCHAR2(50),
  "ICON_MENU_ID"  NUMBER(11, 0),
  "ORDER_"        NUMBER(6, 0),
  "CREATED_DATE"  DATE,
  "UPDATED_DATE"  DATE,
  "CREATED_BY_ID" NUMBER(11, 0),
  "UPDATED_BY_ID" NUMBER(11, 0)
);

CREATE SEQUENCE "CRM"."SEQ_PC_INFO_ID" INCREMENT BY 1 START WITH 1 MAXVALUE 999999999999999999999999999 MINVALUE 1 NOCYCLE CACHE 20 ORDER;
CREATE SEQUENCE "CRM"."SEQ_PC_ICON_MENU_ID" INCREMENT BY 1 START WITH 1 MAXVALUE 999999999999999999999999999 MINVALUE 1 NOCYCLE CACHE 20 ORDER;
CREATE SEQUENCE "CRM"."SEQ_PC_USER_ICON_MENU_ID" INCREMENT BY 1 START WITH 1 MAXVALUE 999999999999999999999999999 MINVALUE 1 NOCYCLE CACHE 20 ORDER;


-- MS_MESSAGE_RECORD


CREATE TABLE "CRM"."MS_MESSAGE_RECORD" (
  "ID"  NUMBER(20,0) NOT NULL,
  "OPENID"  VARCHAR2(32),
  "VIN" VARCHAR2(18),
  "MOBILE"  NUMBER(11,0),
  "MSG_CLASS" VARCHAR2(50),
  "MSG_TYPE" VARCHAR2(50),
  "CONTENT_ID" NUMBER(20,0),
  "INVALID_TIME" DATE,
  "PUSH_CHANNEL" VARCHAR2(50),
  "SEND_STATUS" VARCHAR2(50),
  "SEND_RESULT" VARCHAR2(1000),
  "MSG_SOURCE" VARCHAR2(50),
  "SOURCE_CHANNEL" VARCHAR2(50),
  "CREATED_DATE" DATE,
  "UPDATED_DATE" DATE,
  "CREATED_BY_ID" NUMBER(11,0),
  "UPDATED_BY_ID" NUMBER(11,0),
  PRIMARY KEY("ID")
);
COMMENT ON COLUMN "CRM"."MS_MESSAGE_RECORD"."OPENID" IS '用户的微信OPENID';
COMMENT ON COLUMN "CRM"."MS_MESSAGE_RECORD"."VIN" IS '客户的VIN码';
COMMENT ON COLUMN "CRM"."MS_MESSAGE_RECORD"."MOBILE" IS '手机号';
COMMENT ON COLUMN "CRM"."MS_MESSAGE_RECORD"."MSG_CLASS" IS '消息种类，公告消息，个人消息';
COMMENT ON COLUMN "CRM"."MS_MESSAGE_RECORD"."MSG_TYPE" IS '消息类型，如：活动消息、推广消息。页面根据这个类型呈现不一样的样式';
COMMENT ON COLUMN "CRM"."MS_MESSAGE_RECORD"."CONTENT_ID" IS '消息发送内容关联ID';
COMMENT ON COLUMN "CRM"."MS_MESSAGE_RECORD"."INVALID_TIME" IS '消息失效时间';
COMMENT ON COLUMN "CRM"."MS_MESSAGE_RECORD"."PUSH_CHANNEL" IS '消息发送出去的推送渠道，如：微信平台、短信平台、个人中心';
COMMENT ON COLUMN "CRM"."MS_MESSAGE_RECORD"."SEND_STATUS" IS '发送状态（待发送、发送中、发送成功、发送失败、部分失败）';
COMMENT ON COLUMN "CRM"."MS_MESSAGE_RECORD"."SEND_RESULT" IS '发送结果（主要记录失败原因）';
COMMENT ON COLUMN "CRM"."MS_MESSAGE_RECORD"."MSG_SOURCE" IS '消息发送的来源，可以是接口调用，也可以使人工发送，用于记录一下。';
COMMENT ON COLUMN "CRM"."MS_MESSAGE_RECORD"."SOURCE_CHANNEL" IS '消息来源渠道（由谁调用的）';

CREATE SEQUENCE "CRM"."SEQ_MS_MESSAGE_RECORD_ID" INCREMENT BY 1 START WITH 1 MAXVALUE 999999999999999999999999999 MINVALUE 1 NOCYCLE CACHE 20 ORDER;

-- MS_MESSAGE_CONTENT

CREATE TABLE "CRM"."MS_MESSAGE_CONTENT" (
 "ID" NUMBER(20,0) NOT NULL,
 "MSG_TYPE" VARCHAR2(50),
 "PUSH_CHANNEL" VARCHAR2(50),
 "INVALID_TIME" DATE,
 "SEND_STATUS" VARCHAR2(50),
 "CONTENT" BLOB,
 "CREATED_DATE" DATE,
 "UPDATED_DATE" DATE,
 "CREATED_BY_ID" NUMBER(11,0),
 "UPDATED_BY_ID" NUMBER(11,0),
 "OPENID"  VARCHAR2(32),
 "VIN" VARCHAR2(18),
 "MOBILE"  NUMBER(11,0),
 "MESSAGE_TEMPLATE_ID"  NUMBER(20,0),
 "READ_COUNT"  NUMBER(20,0),
 "MSG_CLASS" VARCHAR2(50),
  PRIMARY KEY("ID")
);
COMMENT ON COLUMN "CRM"."MS_MESSAGE_CONTENT"."ID" IS '物理主键';
COMMENT ON COLUMN "CRM"."MS_MESSAGE_CONTENT"."OPENID" IS '用户的微信OPENID';
COMMENT ON COLUMN "CRM"."MS_MESSAGE_CONTENT"."VIN" IS '客户的VIN码';
COMMENT ON COLUMN "CRM"."MS_MESSAGE_CONTENT"."MOBILE" IS '手机号';
COMMENT ON COLUMN "CRM"."MS_MESSAGE_CONTENT"."MSG_CLASS" IS '消息种类，公告消息，个人消息';
COMMENT ON COLUMN "CRM"."MS_MESSAGE_CONTENT"."MSG_TYPE" IS '消息类型，如：活动消息、推广消息。页面根据这个类型呈现不一样的样式';
COMMENT ON COLUMN "CRM"."MS_MESSAGE_CONTENT"."PUSH_CHANNEL" IS '消息发送出去的推送渠道,多个渠道使用,分割，如：微信、短信平台、个人中心';
COMMENT ON COLUMN "CRM"."MS_MESSAGE_CONTENT"."INVALID_TIME" IS '消息失效时间';
COMMENT ON COLUMN "CRM"."MS_MESSAGE_CONTENT"."SEND_STATUS" IS '发送状态，待发送、发送中、发送成功、发送失败、部分失败';
COMMENT ON COLUMN "CRM"."MS_MESSAGE_CONTENT"."CONTENT" IS '消息内容';
COMMENT ON COLUMN "CRM"."MS_MESSAGE_CONTENT"."MESSAGE_TEMPLATE_ID" IS '对应的模板消息ID';
COMMENT ON COLUMN "CRM"."MS_MESSAGE_CONTENT"."MSG_CLASS" IS '消息阅读总计';

CREATE SEQUENCE "CRM"."SEQ_MS_MESSAGE_CONTENT_ID" INCREMENT BY 1 START WITH 1 MAXVALUE 999999999999999999999999999 MINVALUE 1 NOCYCLE CACHE 20 ORDER;

-- MS_READ_RECORD

CREATE TABLE "CRM"."MS_READ_RECORD" (
  "ID" NUMBER(20,0),
  "CONTENT_ID" NUMBER(20,0),
  "READ_TIME" DATE,
  "OPEN_ID" VARCHAR2(40),
  "VIN" VARCHAR2(20),
  "MOBILE" VARCHAR2(20),
  "SOURCE_CHANNEL" VARCHAR2(50),
  "CREATED_DATE" DATE,
  "UPDATED_DATE" DATE,
  "CREATED_BY_ID" NUMBER(11,0),
  "UPDATED_BY_ID" NUMBER(11,0),
  PRIMARY KEY("ID")
);
COMMENT ON COLUMN "CRM"."MS_READ_RECORD"."CONTENT_ID" IS '消息发送内容';
COMMENT ON COLUMN "CRM"."MS_READ_RECORD"."READ_TIME" IS '阅读时间';
COMMENT ON COLUMN "CRM"."MS_READ_RECORD"."OPEN_ID" IS '用户信息之一:openId';
COMMENT ON COLUMN "CRM"."MS_READ_RECORD"."VIN" IS '用户信息之一:vin码';
COMMENT ON COLUMN "CRM"."MS_READ_RECORD"."MOBILE" IS '用户信息之一:手机号';
COMMENT ON COLUMN "CRM"."MS_READ_RECORD"."SOURCE_CHANNEL" IS '记录来源：个人中心或其他渠道';

CREATE SEQUENCE "CRM"."SEQ_MS_READ_RECORD_ID" INCREMENT BY 1 START WITH 1 MAXVALUE 999999999999999999999999999 MINVALUE 1 NOCYCLE CACHE 20 ORDER;

-- MS_MESSAGE_TEMPLATE_PARAMS

CREATE TABLE "CRM"."MS_MESSAGE_TEMPLATE_PARAMS" (
  "ID" NUMBER(20,0) NOT NULL,
  "PARAM_KEY" VARCHAR2(20),
  "DATA_TYPE" VARCHAR2(20),
  "KEY_DESC" VARCHAR2(200),
  "TEMPLATE_ID" NUMBER(20,0),
  "CREATED_DATE" DATE,
  "UPDATED_DATE" DATE,
  "CREATED_BY_ID" NUMBER(11,0),
  "UPDATED_BY_ID" NUMBER(11,0),
  PRIMARY KEY("ID")
);
COMMENT ON COLUMN "CRM"."MS_MESSAGE_TEMPLATE_PARAMS"."PARAM_KEY" IS '参数key值';
COMMENT ON COLUMN "CRM"."MS_MESSAGE_TEMPLATE_PARAMS"."DATA_TYPE" IS '数据类型：如Sting\Number 与java类型保持一致';
COMMENT ON COLUMN "CRM"."MS_MESSAGE_TEMPLATE_PARAMS"."KEY_DESC" IS 'key描述，用于描述这个key的含义';
COMMENT ON COLUMN "CRM"."MS_MESSAGE_TEMPLATE_PARAMS"."TEMPLATE_ID" IS '所属的模板';

CREATE SEQUENCE "CRM"."SEQ_MS_MSG_TEMPLATE_PARAMS_ID" INCREMENT BY 1 START WITH 1 MAXVALUE 999999999999999999999999999 MINVALUE 1 NOCYCLE CACHE 20 ORDER;

-- MS_MESSAGE_TEMPLATE_PARAMS

CREATE TABLE "CRM"."MS_MESSAGE_TEMPLATE" (
  "ID" NUMBER(20,0) NOT NULL,
  "NAME" VARCHAR2(200),
  "CODE" VARCHAR2(50),
  "CONTENT" CLOB,
  "TEMPLATE_TYPE" VARCHAR2(50),
  "USE_CHANNEL" VARCHAR2(50),
  "CREATED_DATE" DATE,
  "UPDATED_DATE" DATE,
  "CREATED_BY_ID" NUMBER(11,0),
  "UPDATED_BY_ID" NUMBER(11,0),
  PRIMARY KEY("ID")
);
COMMENT ON COLUMN "CRM"."MS_MESSAGE_TEMPLATE"."NAME" IS '模板名称';
COMMENT ON COLUMN "CRM"."MS_MESSAGE_TEMPLATE"."CODE" IS '模板代码，微信模板采用微信系统的代码，自定义的模板添加C开头前缀，区分微信系统的模板代码';
COMMENT ON COLUMN "CRM"."MS_MESSAGE_TEMPLATE"."TEMPLATE_TYPE" IS '模板分类，通过数据字典实现';
COMMENT ON COLUMN "CRM"."MS_MESSAGE_TEMPLATE"."USE_CHANNEL" IS '允许使用的渠道，如：微信，个人中心。多个渠道使用,分割。';

CREATE SEQUENCE "CRM"."SEQ_MS_MESSAGE_TEMPLATE_ID" INCREMENT BY 1 START WITH 1 MAXVALUE 999999999999999999999999999 MINVALUE 1 NOCYCLE CACHE 20 ORDER;
